# Generated by Django 3.0.7 on 2020-06-14 22:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom_image', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BasePage')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'blog.basepage'),
        ),
        migrations.CreateModel(
            name='PostPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BasePage')),
                ('date', models.DateField(default=datetime.datetime.today, help_text='Date when the post will be posted', verbose_name='Post date')),
                ('excerpt', models.CharField(help_text="Post's summary, maximum 255 characters", max_length=255, verbose_name='Excerpt')),
                ('body', wagtail.core.fields.RichTextField(help_text='It will be the main content of your post', verbose_name="Post's Body")),
                ('header_image', models.ForeignKey(help_text='Header Image. It will be used after the title in the post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custom_image.CustomImage', verbose_name='Header Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.basepage',),
        ),
    ]
