# Generated by Django 3.0.7 on 2020-06-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindexpage_postpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('color', models.CharField(help_text='Category color', max_length=7)),
            ],
            options={
                'verbose_name': 'Blog category',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
    ]
